### ISSUE TITLE
Introduce App Theme 

### ISSUE THREAD

**Issue by alexander-dejeu** [Mintri1199/Industry_Collaboration_Project#16]
I think there is an opportunity to more safely support colors, images, and fonts that will enable a stronger design language system (DLS).  I went back through some other PRs and captured the core concepts here.

**Colors**
Instead of creating an extension for UIColor, can we create a more abstract way of capturing what we need these UIColors for, IE, a theme! Themes can include colors, fonts, images, etc. A very concrete example of the advantage of using themes would be if we wanted to introduce a dark mode, we would not want to have to change everything / need "darkModeNavBarBlue" instead we just want to have it be a protocol that can be conformed to and then all of our UI updates... or so is the thought.

At a super high level:
```
struct Theme {
  let colors: ColorSchema
  let imageAssets: ImageAsset
  let fontSchema: FontSchema
  ...
}  
protocol ColorSchema {
  // MARK: - Primary Colors
  var black: UIColor { get }
  var white: UIColor { get }
}
...

struct DefaultColors: ColorSchema {
  // Conform to protocol
}

struct DarkModeColors: ColorSchema {
  // Conform to schema - theme can manage which to use :) 
}
```

**Images**

```
protocol ImageAsset {
  var smallLogo: UIImage { get }
struct DefaultImageAsset: ImageAsset {
  var smallLogo: UIImage {
    return #imageLiteral(resourceName: "small_logo")
  }
```
This works great as it is very easy to make sure all the assets defined actually create a non empty image and therefore will not result in random parts of the app missing images if an asset name is changed or a typo is created in the view

**Fonts**
Fonts are a bit more involved, but I also see the advantage here as it allows the developers / designers to develop a design language system that is super flexible and very easy to change, update, and experiment with:

```
enum FontStyle {
  case regular
  case bold
  case semiBold
  case medium
  case light
}

protocol FontSchema {
  /* Basic fonts */
  var regular10: UIFont { get }
  var regular12: UIFont { get }

  /* Font templates */
  var titleRegular: UIFont { get }
  ...
}

struct DefaultFontSchema: FontSchema {
  /* Basic fonts */
  var regular10: UIFont {
    return font(size: 10)
  }

  var regular12: UIFont {
    return font(size: 12)
  }

  /* Font templates */
  var titleRegular: UIFont {
    return bold24
  }

    private func font(style: FontStyle, size: CGFloat) -> UIFont {
    var name: String
    switch style {
    case .bold:
      name = "YourFont-Bold"
    case .regular:
      name = "YourFont"
    case .semiBold:
      name = "YourFont-SemiBold"
    case .medium:
      name = "YourFont-Medium"
    case .light:
      name = "YourFont-Light"
    }
    return UIFont(name: name, size: size)!
  }
}
```

**Comment by alexander-dejeu** [comment]
Opened a PR

**Comment by alexander-dejeu** [comment]
Hey @Mintri1199! Any concerns on this PR?

**Comment by Mintri1199** [comment]
@alexander-dejeu Hey sorry for the late reply, I haven't been checking the repo since I was busy with following up with recruiters. Other than that I think these changes will benefit the project. So I will get on it and hopefully get it done by this weekend.

Other things I'll like to do after resolving this issues is creating/updating the wiki tab of this project to help other contributors to figure out how to modify the Theme

**Comment by alexander-dejeu** [comment]
No worries! Hope the interview process is treating you well! 👍 

Agreed that improving the wiki with info on how to update / modify would be good! Any blockers on first merging the code change and then introducing the wiki page in a separate PR?

**Comment by Mintri1199** [comment]
@alexander-dejeu I'm currently researching on atomic design system which is very similar with this idea of streamlining the creation of UI. I'll keep you updated on the progress of research.
