### ISSUE TITLE
Introduce String Localization

### ISSUE THREAD

**Issue by alexander-dejeu** [Mintri1199/Industry_Collaboration_Project#17]
Introduce `Localizable.strings` file in order to prevent just hardcoding string assets.

**Benefits**
* Internationalization support is easier the earlier it is completed
* Support more languages as needed
* Move all string assets to a single place for review / commentary instead of in the code

**Comment by alexander-dejeu** [comment]
Opened a PR - #18

**Comment by alexander-dejeu** [comment]
Hey @Mintri1199! Any concerns on this PR?

**Comment by Mintri1199** [comment]
@alexander-dejeu No concern at all, I think it is a wonderful addition to the project. I'll close this issue.
