### ISSUE TITLE
[Request] Use 2 spaces instead of 4 for indentation

### ISSUE THREAD

**Issue by alexander-dejeu** [Mintri1199/Industry_Collaboration_Project#20]
Hey Team! 

Any concerns moving to use 2 spaces for indentation instead of 4? It will make the horizontal space more condense and readable IMO.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/13122645/72758604-13ae4300-3b88-11ea-98f2-9645079152c9.png">

Thoughts?

**Comment by Mintri1199** [comment]
@alexander-dejeu  This is something I discussed with the rest of the team in the beginning of development and I refused due to familiarity. But I can ask the other members again to see if their opinion changed. Other than that I am fully supportive of this change.

**Comment by alexander-dejeu** [comment]
Sounds good - let me know if you decide to opt for this 👍 

Some other style guides for inspiration 
[Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
[Google Swift Style Guide](https://google.github.io/swift/#horizontal-alignment)

**Comment by alexander-dejeu** [comment]
@Mintri1199 put up a PR to [add Swiftformat](https://github.com/Mintri1199/Industry_Collaboration_Project/pull/21/files) Currently it is 2 spaces, but I can change to 4?

**Comment by Mintri1199** [comment]
@alexander-dejeu I think its safe to change it to 2 now. With that being said though I would like to spend some time looking over Swiftformat before merging it to master
